name: 自动部署

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: 检出源代码
        uses: actions/checkout@v4
        with:
          path: 'source'
          fetch-depth: 0
          
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 安装 Hexo 和依赖
        working-directory: ./source
        run: |
          npm install hexo-cli -g
          if [ ! -f package-lock.json ] && [ ! -f yarn.lock ]; then
            npm install --package-lock-only
          fi
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          
      - name: 生成静态文件
        working-directory: ./source
        run: |
          export TZ='Asia/Shanghai'
          hexo clean
          hexo bangumi -u || true  # 忽略可能的错误
          hexo generate
          
          # 验证生成结果
          if [ ! -d "public" ]; then
            echo "##[error]public 目录未生成!"
            echo "当前目录内容:"
            ls -la
            exit 1
          fi
          
      - name: 准备部署目录
        run: |
          mkdir -p deploy
          cp -r source/public/. deploy/ || cp -r public/. deploy/  # 双重保险
          touch deploy/.nojekyll
          [ -f source/CNAME ] && cp source/CNAME deploy/CNAME || true
          
      - name: 验证部署内容
        run: |
          echo "部署目录内容:"
          ls -la deploy
          [ -f deploy/index.html ] || { echo "##[error]index.html 缺失!"; exit 1; }
          
      - name: 配置 Git 身份
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          
      - name: 直接 Git 部署
        run: |
          cd deploy
          git init
          git add .
          git commit -m "部署: ${{ github.sha }}"
          
          # 使用推荐的认证方式
          git remote add origin "https://github.com/Luvicii/Luvicii.github.io.git"
          git push -f origin HEAD:main
          
          # 备选认证方式
          # git push -f "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Luvicii/Luvicii.github.io.git" HEAD:main
