name: 自动部署

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: 安装 Hexo
        run: npm install hexo-cli -g

      - name: 安装依赖
        run: npm ci

      - name: 生成静态文件
        run: |
          export TZ='Asia/Shanghai'
          hexo clean
          hexo bangumi -u
          hexo generate

      - name: 验证生成结果
        run: |
          [ -f public/index.html ] || exit 1
          echo "生成完成，共 $(find public -type f | wc -l) 个文件"

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: Luvicii/Luvicii.github.io
          branch: main
          folder: public
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
          single-commit: true
          target-folder: /
          commit-message: "部署: ${{ github.sha }} [通过Github Actions]"
