name: 自动部署

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: 检出源代码
        uses: actions/checkout@v4
        with:
          path: 'source'
          fetch-depth: 0  # 获取完整历史
          
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # 禁用自动缓存（手动处理）
          
      - name: 生成锁文件（如缺失）
        working-directory: ./source
        run: |
          # 如果锁文件不存在则创建
          if [ ! -f package-lock.json ] && [ ! -f yarn.lock ]; then
            npm install --package-lock-only
          fi
          
      - name: 安装 Hexo
        run: npm install hexo-cli -g
        
      - name: 安装项目依赖
        working-directory: ./source
        run: |
          # 优先使用 package-lock.json
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          
      - name: 生成静态文件
        working-directory: ./source
        run: |
          export TZ='Asia/Shanghai'
          hexo clean
          hexo bangumi -u
          hexo generate
          
      - name: 准备部署目录
        run: |
          mkdir -p deploy
          # 复制生成的静态文件
          cp -r source/public/* deploy/
          
          # 添加必要的 GitHub Pages 文件
          touch deploy/.nojekyll
          [ -f source/CNAME ] && cp source/CNAME deploy/CNAME
          
      - name: 直接 Git 部署（100% 可靠）
        run: |
          cd deploy
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "部署: ${{ github.sha }} [通过Github Actions]"
          
          # 使用 GITHUB_TOKEN 认证
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/Luvicii/Luvicii.github.io.git" HEAD:main
